apiVersion: v1
kind: ConfigMap
metadata:
  name: consentledger-config
  namespace: consentledger
  labels:
    app.kubernetes.io/name: consentledger
data:
  SPRING_PROFILES_ACTIVE: "local"
  SERVER_PORT: "8080"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "consentledger"
  JDBC_URL: "jdbc:postgresql://postgres:5432/consentledger"
  LOGGING_LEVEL_ROOT: "INFO"
